### ISSUE TITLE
param file for runCommandline not working on trim_galore

### ISSUE THREAD

**Issue by rfarouni** [tgirke/systemPipeR#1]
Hi,
I would like to do adapter trimming using *trim_galore*, but since it does not accept an output file name as an argument (only output directory), I am unable to run the *runCommandline* function from within R. I tried changing the value of outfile1 (<FileName1>) to NA and also tried removing it but nothing worked. Is there a way to leave the <FileName1> value empty?

```
PairSet	Name	Value
type	system	TRUE
modules		
software	NA	trim_galore
other	NA	--length 50 --phred64 
outfile1	-o	<FileName1>
outfile1	path	./data/trimmed
reference	NA	NA
infile1	NA	<FileName1>
infile1	path	NA
infile2	NA	<FileName2>
infile2	path	NA

```

**Comment by tgirke** [comment]
Take a look at the tophat param file where the situation is similar: https://goo.gl/p15kQB. If it doesn't work for you then I can add a trim_galore sample *.param file later next week. Right now I have to focus on some internal deadlines. In the next major release of systemPipeR these param files will semi auto-generated so that the user doesn't have to deal with these details anymore.

**Comment by rfarouni** [comment]
Thanks @tgirke. I tried many configuration but nothing seemed to work.  Here is my last attempt
```
PairSet	Name	Value
type	system	TRUE
modules		
software	NA	trim_galore
other	NA	--length 50 --phred64 
outfile1	-o	<FileName1>
outfile1	path	./results/trimmed/
outfile1	remove	NA
outfile1	append	.trimmed
outfile1	outextension	.trimmed/trimmed.fq.gz
reference	NA	NA
infile1	NA	<FileName1>
infile1	path	NA
infile2	NA	<FileName2>
infile2	path	NA
```

**Comment by tgirke** [comment]
Sorry for the delay. I didn't get to this before the holidays. - i have now added a `trim_galor.param` and a `trim_galore_run.sh` file to systemPipeRdata [here](https://github.com/tgirke/systemPipeRdata/tree/master/inst/extdata/param). Please download both of them to your `param` directory on the same level where you have the `data` and `results` directories of your analysis project. In addition, I committed a small update to systemPipeR (version 1.9.2) to make things easier. After installing this version from GitHub (as shown [here](https://github.com/tgirke/systemPipeR)) or Bioc, you should be able to run `git_galore` from systemPipeR like this:
```
library(systemPipeR) # needs to be version >=1.9.2
args <- systemArgs(sysma="./param/trim_galore.param", mytargets="targets.txt") 
runCommandline(args, make_bam=FALSE)
writeTargetsout(x=args, file="targets_trim.txt") # generates targets file for trimmed FASTQ files
```

Please note the argument settings for `trim_galore` are defined in `trim_galor_run.sh`. If you don't use a module system then please also remove the module load commands at the beginning of this file. 

The next upgrade should make those things much easier. I am optimistic to have a functional version of this upgrade committed to the developer branch by the end of Jan or early Feb.

Thomas

**Comment by rfarouni** [comment]
Thanks!
