### ISSUE TITLE
Error when trying to preprocessReads() : "Error: logical subscript contains NAs"

### ISSUE THREAD

**Issue by jsalsager** [tgirke/systemPipeR#12]
Hi, 

This issue is cross posted on the bioconductor support page. There I have posted a full example of my code. But basically when I try to use preprocessReads() with the standard protocol, it runs into an error saying "Error: logical subscript contains NAs". Do you know where I am going wrong? All my paths are correct and I have verified my targetsPE.txt file and trimPE.param files.

Thanks so much! 

Simon 

https://support.bioconductor.org/p/115482/

**Comment by dcassol** [comment]
Hi @jsalsager, 
I'm going to close this for now, since I continued the discussion on the [Bioconductor support page](https://support.bioconductor.org/p/115482/#115596). Feel free to re-open.
Cheers,
