### ISSUE TITLE
Construct SYSargs2 object from CWl param, CWL input, and targets files

### ISSUE THREAD

**Issue by cbiOPela** [tgirke/systemPipeR#18]
Hi all!

Congrats for your fantastic package!

I'am trying to use your tool with my own data following your recommendations. I get this error in the step specified in the title. Until renderWF everything is OK.
My question is: what is needed by renderWF in inputvars (FileName and SampleName) 

I paste last lines of the code i'm running 

dir_path <- paste0(getwd(),"/param/cwl/preprocessReads/trim-se")
dir_path
trim <- loadWorkflow(targets = targetspath, wf_file = "trim-se.cwl", input_file = "trim-se.yml", 
                     dir_path = dir_path)

**trim <- renderWF(trim, inputvars=c(FileName="data/SRR1016916", SampleName="M1A"))**

And the error printed:

**Error in if (basecommand[1] == "mkdir") { : argument is of length zero**

Thank you in advance!!

**Comment by dcassol** [comment]
Hi @cbiOPela, 
Thank you for using ```systemPipeR```!

Could you please provide the output of  ```sessionInfo()``` executed in an R session right after the error occurred?

Also, note that in the argument ```inputvars```, the variable names defined in the ```trim.yml``` as ```_FASTQ_PATH1_``` and ```_SampleName_```, need to match the column names defined in the targets file (in your case, ```targetspath```).
It is possible to assign NULL in the targets argument (```loadWorkflow``` function) to run the pipeline without 'targets' file. This case can be useful for running a specific command-line tool, which does not require different input files (for example, when we create the index for the alignment).

**Comment by dcassol** [comment]
Hello @cbiOPela,
I'm going to close this for now, as we haven't heard back from you in a while. 
Feel free to re-open if you have any additional questions.
Cheers,
