### ISSUE TITLE
Not getting the Bam files

### ISSUE THREAD

**Issue by ishaaq34** [tgirke/systemPipeR#68]
I managed to run that but I could not get bam files. I only got the sam files. 

![toshow](https://user-images.githubusercontent.com/47107221/146957081-b3c9c464-24ac-4c59-ba0e-b2eeebf709f4.png)

Could you please help out here . 
@dcassol

**Comment by dcassol** [comment]
You need to explicitly request that in the `runCommandline()` function. 
```
?runCommandline
args <- runCommandline(args, make_bam = TRUE, del_sam=FALSE, dir = TRUE)
```
Here you have 3 main possibilities: 1) to detect SAM file outputs and convert them to sorted and indexed BAM files; 2) Keep the sam files; 3) to create a subfolder for all the outputs or not.

**Comment by dcassol** [comment]
Hello @ishaaq34,
I'm going to close this for now!
Feel free to re-open if you have any additional questions.
Cheers,
Daniela
