### ISSUE TITLE
Error in runWF(sal)

### ISSUE THREAD

**Issue by pwang24** [tgirke/systemPipeR#73]
Hello,

I got an error when I follow the  RIBO-Seq Workflow Template.

**I run the code in R as following:**
> library(systemPipeR)
> systemPipeRdata::genWorkenvir(workflow = "riboseq", mydirname = "riboseq")
> setwd("riboseq")
> targetspath <- system.file("extdata", "targetsPE.txt", package = "systemPipeR")
> targets <- read.delim(targetspath, comment.char = "#")[, 1:4]
> targets
> library(systemPipeR)
> sal <- SPRproject()
> sal
> appendStep(sal) <- LineWise(code = {
+     library(systemPipeR)
+     library(rtracklayer)
+     library(GenomicFeatures)
+     library(ggplot2)
+     library(grid)
+     library(BiocParallel)
+     library(DESeq2, quietly = TRUE)
+     library(ape, warn.conflicts = FALSE)
+     library(edgeR)
+     library(biomaRt)
+     library(BBmisc)  # Defines suppressAll()
+     library(pheatmap)
+     library(BiocParallel)
+ }, step_name = "load_SPR")
> appendStep(sal) <- SYSargsList(step_name = "preprocessing", targets = "targetsPE.txt",
+                                dir = TRUE, wf_file = "preprocessReads/preprocessReads-pe.cwl",
+                                input_file = "preprocessReads/preprocessReads-pe_riboseq.yml",
+                                dir_path = system.file("extdata/cwl", package = "systemPipeR"),
+                                inputvars = c(FileName1 = "_FASTQ_PATH1_", FileName2 = "_FASTQ_PATH2_",
+                                              SampleName = "_SampleName_"), dependency = c("load_SPR"))
> sal <- runWF(sal)
**But I got the errors like this:**
Running Step:  load_SPR 
Running Session: Management 
  |                                                                                                                       |   0%Loading 
required package: AnnotationDbi

Attaching package: ‘grid’

The following object is masked from ‘package:Biostrings’:

    pattern

Attaching package: ‘DESeq2’

The following object is masked from ‘package:systemPipeR’:

    results

  |=======================================================================================================================| 100%
Error in runWF(sal) : Caught an error, stop workflow!

Could you please help me to find the answer? 
Thank you!

**Comment by tgirke** [comment]
Unless I overlooked a typo in your code, I am not able to reproduce your error when using the corresponding code from the vignette [here](http://www.bioconductor.org/packages/devel/data/experiment/vignettes/systemPipeRdata/inst/doc/systemPipeRIBOseq.html). Perhaps check whether all the libraries/packages that are loaded in the first code chunk you showing are indeed installed on your system. If any is missing then this could trigger such an error. If so more explicit error message could be triggered in the future. If this doesn't fix it then make sure you have the latest R/Bioc version and packages installed on your system. If you need more help then it would be import to send the output of `sessionInfo()` executed right after experiencing the error.  

Please note that you can run the workflow without going through the individual steps in its entirety like this:
```r 
sal <- importWF(sal, file_path = "systemPipeRIBOseq.Rmd")
runWF(sal)
```
Instructions on this are in the main vignette [here](https://bioconductor.org/packages/release/bioc/vignettes/systemPipeR/inst/doc/systemPipeR_workflows.html#5_Ribo-Seq_Workflow).
